### ISSUE TITLE
cd.aux not found! and Error: Unknown argument: "max_smp_vol" 

### ISSUE THREAD

**Issue by Justan6** [iquasere/reCOGnizer#11]
Hello. 
I encountered the error below, and I think all the cd.aux are not found! And Error: Unknown argument: "max_smp_vol" :

Error: Unknown argument: "max_smp_vol"                                               
cat: 'recognizer_output/blast/KOG_*_aligned.blast': No such file or directory
2023-01-02 12:57:22: Organizing annotation results             
cat: 'recognizer_output/blast/CDD_*_aligned.blast': No such file or directory
[1/8] Handling CDD annotation                                           
cat: 'recognizer_output/blast/Pfam_*_aligned.blast': No such file or directory
[2/8] Handling Pfam annotation                                
cat: 'recognizer_output/blast/NCBIfam_*_aligned.blast': No such file or directory
[3/8] Handling NCBIfam annotation                                                                 
cat: 'recognizer_output/blast/Protein_Clusters_*_aligned.blast': No such file or directory
[4/8] Handling Protein_Clusters annotation   
cat: 'recognizer_output/blast/Smart_*_aligned.blast': No such file or directory
[5/8] Handling Smart annotation                                         
cat: 'recognizer_output/blast/TIGRFAM_*_aligned.blast': No such file or directory
[6/8] Handling TIGRFAM annotation                                      
cat: 'recognizer_output/blast/COG_*_aligned.blast': No such file or directory    
[7/8] Handling COG annotation                                                        
cat: 'recognizer_output/blast/KOG_*_aligned.blast': No such file or directory
[8/8] Handling KOG annotation                                           
/home/nwezejus/miniconda3/envs/reCOGnizer/bin/recognizer.py:844: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  xlsx_report.save()

**Comment by Justan6** [comment]
Solved!

**Comment by danadanaanaa** [comment]
Hi, similar problem here, may I know how to solve the issue? 

2023-01-18 00:54:19: Organizing annotation results
[1/8] Handling CDD annotation
[2/8] Handling Pfam annotation
[3/8] Handling NCBIfam annotation
[4/8] Handling Protein_Clusters annotation
[5/8] Handling Smart annotation
[6/8] Handling TIGRFAM annotation
[7/8] Handling COG annotation
[8/8] Handling KOG annotation
/Users/opt/anaconda3/envs/recognizer/bin/recognizer.py:844: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  xlsx_report.save()
2023-01-18 00:54:20: reCOGnizer analysis finished in 00h05m09s

Many thanks.

**Comment by iquasere** [comment]
@danadanaanaa, what is the problem there? reCOGnizer analysis seems to have finished correctly.

**Comment by danadanaanaa** [comment]
> @danadanaanaa, what is the problem there? reCOGnizer analysis seems to have finished correctly.

Hi, thank you so much for replying, the problem seems that it poped out "FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
xlsx_report.save()",

but I am not sure if it was the reason that none protein sequences were annotated, the results files were empty.

**Comment by iquasere** [comment]
No, that warning is only warning me that soon I'll have to remove the exporting of results to Excel from reCOGnizer.

The tool seems to be working fine, but if you send me your **input dataset** and your **reCOGnizer command**, I may run it myself and see if something is amiss.

**Comment by danadanaanaa** [comment]
> No, that warning is only warning me that soon I'll have to remove the exporting of results to Excel from reCOGnizer.
> 
> The tool seems to be working fine, but if you send me your **input dataset** and your **reCOGnizer command**, I may run it myself and see if something is amiss.

Hi, great appreciate for your help, how could I send you the dataset, it is the one containing 10 bacterial WGS genomes.
