### ISSUE TITLE
Struggling to install

### ISSUE THREAD

**Issue by vcoyne1** [iquasere/reCOGnizer#13]
Hi,

I run the command below as suggested for installation:
(base) PS C:\Users\verno> conda install -c conda-forge -c bioconda recognizer

Here's what I get:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

I can't get past this issue - any advice would be great.

Thanks!

**Comment by vcoyne1** [comment]
I have now managed to install using the install.bash option, but I cannot execute. It would be very useful if a more detailed description of the application installation process as well as a Troubleshooting section. I have now spent far too much time on trying to get reCOGnizer running.

**Comment by vcoyne1** [comment]
Success at last! Finally installed and running.

**Comment by iquasere** [comment]
As future tip, reCOGnizer is better installed with mamba. Conda installer is getting worse every year, and it seems it can't install reCOGnizer anymore
