### ISSUE TITLE
fun.tsv cant be found? 

### ISSUE THREAD

**Issue by Ethnobotaniker** [iquasere/reCOGnizer#16]
Hello i just installed and wanted to try reCOGnizer, but i have a problem.
I installed as explained from source and setup the database.
But when i want to execute a anotation i get the following error:

FileNotFoundError: [Errno 2] No such file or directory: '/group/opt/reCOGnizer/fun.tsv' 

I am calling the program as follows:

recognizer.py -f ../../S1.hg38unaligned.contigs.fraggenescan.w0.faa -o . --resources-directory /group/db/recognizer/

where should this file be located?
should it be inside the folder were all the databses are stored?

I am using the latest version.

I would appreciate some help

thanks in advance.

**Comment by iquasere** [comment]
Hey there! Did you run reCOGnizer one time with the `-dr` flag? It needs to be run at least once with that option so it downloads the resources on its first run.

**Comment by Ethnobotaniker** [comment]
Hello, thanks for your fast answer!
yes i downloaded all the references as described in your setup.
i kinda fixed it i think, i found the fun.tsv file in the resources folder in the installation directory and copied it from there into the directory it is expected to be in and then it worked.
i dont know maybe i messed something up during the installation?

**Comment by iquasere** [comment]
It is working in the [tests](https://github.com/iquasere/reCOGnizer/actions/runs/6198725390). Since I can't reproduce it on my end, it might have been some particular aspect with your system. Please don't hesitate raising another issue if it happens again, or any other bug!
