### ISSUE TITLE
Warning: [rpsblast] Query is Empty! error

### ISSUE THREAD

**Issue by EdwinDNavarroMonserrat** [iquasere/reCOGnizer#17]
Hi,

Thanks for putting together this wonderful resource. I've run reCOGnizer before and I am now experiencing an issue with the pipeline suggesting my fasta file has empty queries. I've troubleshooted several things and (e.g., check protein sequence format for unwanted characters, redownloading the databases) it all seems to be fine. When I take a subset of the proteins and run them with different pipelines it seems like the queries are processed just fine.  

I'm attaching my protein fasta file. 

Any thoughts onto why I get this error?
[no_duplicateT6SE.zip](https://github.com/user-attachments/files/16036043/no_duplicateT6SE.zip)

Thanks in advance!

**Comment by iquasere** [comment]
Hey, @EdwinDNavarroMonserrat ! Thank you for reporting on this issue. Can you please put here the command you used to run reCOGnizer, and the output of `recognizer -v`?
