### ISSUE TITLE
Empty results files.

### ISSUE THREAD

**Issue by dale-2024** [iquasere/reCOGnizer#19]
Hi,

My results files are empty (contain headers only). Could you take a look please? Any help will be greatly appreciated.

I installed reCOGnizer as explained in the README and am using a bacterial genome protein fasta from the NCBI as input. Running the command produces the following errors for each database:

```
Created /home/user/Desktop/recognizer/output/asn
Created /home/user/Desktop/recognizer/output/blast
Created /home/user/Desktop/recognizer/output/rpsbproc
Created /home/user/Desktop/recognizer/output/tmp
2024-09-06 10:42:39: Download timestamp found. Files were downloaded at 2024-09-06 09:57:50
2024-09-06 10:42:39: Loading relational tables
2024-09-06 10:42:39: Running annotation with RPS-BLAST and CDD database as reference.
A valid cd split database was found!
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
[rpsblast] ERROR: Invalid argument: -query
cat: '/home/user/Desktop/recognizer/output/blast/CDD_*_aligned.blast': No such file or directory
```

**To Reproduce**
- Input file:
"protein.faa" from GCA_000005845.2, available at:
https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000005845.2/

- Write the command used:
recognizer -f ~/Desktop/recognizer/input/protein.faa -o ~/Desktop/recognizer/output/

**Please complete the following information:**
 - OS: Linux Mint 20.2 Cinnamon
 - Version of reCOGnizer: 1.10.1

**Comment by iquasere** [comment]
It took a lot longer than expected, and I still am not sure what the problem was. However, I could reproduce it on my end, and it was related to the `makeprofiledb` of the `blast` package. I also took the opportunity to revamp the generation of databases, as I saw that there were some differences between how reCOGnizer separated the HMMs (in `.smp` files) into the different databases.

[Version `1.11`](https://github.com/iquasere/reCOGnizer/releases/tag/1.11.0) implements these fixes, and will be available in a short while. reCOGnizer should now be working fine, but please let me know if it still doesn't work.

**Comment by iquasere** [comment]
Nope, still gives same problem. The problem here is that the [cdd.tar.gz](https://ftp.ncbi.nih.gov/pub/mmdb/cdd/cdd.tar.gz) file is not being correctly downloaded by wget sometimes. Other times it works fine. I'll have to try something different.

**Comment by dale-2024** [comment]
Hi João,

Thanks for the update, and all the effort you're putting in to this. I appreciate it. Unfortunate that it's not an easy fix.

I'll let you know how the analysis goes once the new release is ready.

best regards,
Dale

Sent with [Proton Mail](https://proton.me/mail/home) secure email.

**Comment by iquasere** [comment]
So, my suggestion is a bit weird. But if you set up reCOGnizer's databases at a time when NCBI is not as overwhelmed with downloads, it will work well. The command to set up reCOGnizer's databases is the same, i.e., `recognizer -f input_file -o output_directory`.

So my suggestion here is:
1. remove the `~/recognizer_resources` directory - command: `rm -r ~/recognizer_resources`
2. run reCOgnizer again, and see if it fails. If it does, wait some hours, and try again - command: `recognizer -f input_file -o output_directory`

I'm going to put a version out that checks if the databases were correctly downloaded, but I'm currently with a lot of work. I'll try to update reCOgnizer with that, but for your work, I would say this solution is fine. It will build the databases properly, and from then on, reCOGnizer runs well.

Still, if 2-3 tries don't work, let me know. And sorry for this unsatisfactory solution, but it really is dependent on NCBI's availability to provide these files. Still, it only takes one correct download for reCOGnizer to be fully operational.

**Comment by iquasere** [comment]
Just released version `1.11.1`, which I am sure should fix this error - there was still another new aspect of the `cdd.tar.gz` file that I hadn't addressed, because even the tests of reCOGnizer were not reporting on this. Everything seems to be working fine now.

Next monday I am going to compile a list of commands to download the databases directly from [little_endian](https://ftp.ncbi.nih.gov/pub/mmdb/cdd/little_endian/) folder, so these problems can always be bypassed. I'll post those commands here, and will provide an option in reCOGnizer to allow to use those databases directly.

For most users, using those databases will be fine. Only users that want to use the taxonomic workflow of reCOGnizer will have to download through the CDD Tarball.

**Comment by iquasere** [comment]
Concluded by e-mail. The problem seems to have been related to NCBI's servers not being available for providing the files required by reCOGnizer.

**Comment by B-Neil** [comment]
I'm having the same problem: I ran ReCOGnizer, but the final TSV file is empty, it only generated the header.
temporary files: https://we.tl/t-sAnkQ4xAPtVr8fpv

(reco) [jferreira@turing reCOGnizer]$ recognizer -f prot_nao_caracterizadas.fasta -o ./ --debug
Created ./asn
Created ./blast
Created ./rpsbproc
Created ./tmp
2026-04-15 14:56:12: Download timestamp found. Files were downloaded at 2026-04-15 14:24:08
2026-04-15 14:56:12: Loading relational tables
2026-04-15 14:56:13: Replacing spaces with underscores
2026-04-15 14:56:13: Splitting ./tmp/tmp.fasta
2026-04-15 14:56:13: Finished splitting ./tmp/tmp.fasta
2026-04-15 14:56:13: Running annotation with RPS-BLAST and NCBI_Curated database as reference.
A valid Cdd_NCBI split database was found!
2026-04-15 14:56:16: Running annotation with RPS-BLAST and Pfam database as reference.
A valid Pfam split database was found!
2026-04-15 14:56:19: Running annotation with RPS-BLAST and SMART database as reference.
A valid Smart split database was found!
2026-04-15 14:56:21: Running annotation with RPS-BLAST and KOG database as reference.
A valid Kog split database was found!
2026-04-15 14:56:24: Running annotation with RPS-BLAST and COG database as reference.
A valid Cog split database was found!
2026-04-15 14:56:26: Running annotation with RPS-BLAST and PRK database as reference.
A valid Prk split database was found!
2026-04-15 14:56:29: Running annotation with RPS-BLAST and TIGR database as reference.
A valid Tigr split database was found!
2026-04-15 14:56:32: Organizing annotation results
[1/7] Handling NCBI_Curated annotation
[1/7] Handling Pfam annotation
[1/7] Handling SMART annotation
[1/7] Handling KOG annotation
[1/7] Handling COG annotation
[1/7] Handling PRK annotation
[1/7] Handling TIGR annotation
2026-04-15 14:56:32: reCOGnizer analysis finished in 00h00m19s
(reco) [jferreira@turing reCOGnizer]$

**Comment by iquasere** [comment]
The error was fixed, now lets see if the tests go through. I also updated those to check for empty results now
