### ISSUE TITLE
Confusion in the recognizer output

### ISSUE THREAD

**Issue by SrichandanPadhi** [iquasere/reCOGnizer#20]
![image](https://github.com/user-attachments/assets/67603267-5919-45b1-ba57-83eb22e3b53d)

Hi there,
The attached image is the output file (COG_quantification.tsv) from recognizer. Could you please explain what the highlighted column indicate as there is no column heading.

**Comment by iquasere** [comment]
Hey there!

That column is the count of each COG ID identified in your dataset.

The dataframe has to be presented with no header, so it can be used as input to `ktImportText`.

**Comment by SrichandanPadhi** [comment]
Well, thank you so much for your support as always.
