### ISSUE TITLE
Please check download_resources(directory)

### ISSUE THREAD

**Issue by ConstantinV** [iquasere/reCOGnizer#4]
Hi, thank you for your tool!

I am trying to run from scratch with "-rd" option. But it did not download properly.
Could you check you function in my case I closed strings #174 and #175 and changed level of run_command(f'wget {location} -P {directory}') to start upload all resources. 
But I can figure out in which folder this script should be written **'https://bitbucket.org/scilifelab-lts/lts-workflows-sm-metagenomics/raw/screening_legacy/', 'lts_workflows_sm_metagenomics/source/utils/cog2ec.py'**? In the resource folder?

Thank you in advance!

**Comment by iquasere** [comment]
Hi there! And thank you for your interest on reCOGnizer! I am taking a break right now, will return next monday, and will look at this issue first thing! The cog2ec.py script should be in fact on the resources_directory folder, will check if I can reproduce this bug when I come back!

**Comment by iquasere** [comment]
reCOGnizer was not downloading files essential for running rpsbproc. With the release of reCOGnizer, this has been dealt with.

Please feel free to reopen this issue if the problem persists. If you find another bug, please do open a new issue.

Thank you for reporting this!
