### ISSUE TITLE
initial set up

### ISSUE THREAD

**Issue by adeslatt** [iquasere/reCOGnizer#7]
Thank you for your tool - I want to use it to annotate novel sequences and differentiate to cell populations based upon the presence or absence of conserved domains. 

However, I am failing at the first step of setting up the databases -- the cdd.tar.gz gets downloaded but not the other databases.  Instructions for the initial set up do not make this first part clear.

**Comment by iquasere** [comment]
Hi there! 

Sorry you are having problems with reCOGnizer, could you please tell me what is the command you are running? Also, could you please tell the version of the tool you are using?

**Comment by iquasere** [comment]
Hey there! Is reCOGnizer still giving problems?
