### ISSUE TITLE
Version of databases

### ISSUE THREAD

**Issue by CelinePetersen** [iquasere/reCOGnizer#8]
Hi, 

Thanks for the tool. Can you please clarify what database version of Kog is being downloaded? It seems to be 2003 version but it will be quite outdated to use now. It is possible to include https://ftp.ncbi.nih.gov/pub/mmdb/cdd/little_endian/ version of KOG?

**Comment by iquasere** [comment]
Hey there! reCOGnizer obtains the cdd.tar.gz file from the [parent folder](https://ftp.ncbi.nih.gov/pub/mmdb/cdd/) of that little_endian directory, and extracts the SMPs to build either the complete databases (as the ones in little_endian) and/or to separate the SMPs by taxonomy and produce dozens of databases, but in the same format and purpose.

By what I see, that file has the same date of update - ```2021-02-22 20:53``` - as the databases in little_endian, so reCOGnizer is downloading the 2021 version of CDD, and respective databases.
